# Site settings
title: shredow
email: contact@shredow.com
description: >-
  shredow GmbH: Transforming health through technology. We invest in early-stage startups and innovative ideas that create healthier lives and societies. Empowering disruption, progress, and transformation in health and technology.
baseurl: "" # Leave empty for custom domain
url: "https://shredow.com" # Your custom domain

# Build settings
theme: 
plugins: []
  
# Exclude files or directories from Jekyll processing
exclude:
  - README.md
  - .git/
  - .jekyll-cache/
